use travelgene
document=({"user_id":"00000001", "user_name":"liuyancheng", "password":"123456", "email":"liuyancheng@gmail.com", "phone":"4125204000", "birth":new Date('May 16, 1991'),"trip_id":[1,2,3,4,6],"friend_id":["00000002","00000003"],"trip_list":[null],"icon_url":"http://bic.cs.cmu.edu/Students/studentpics/Liu,%20Yancheng.jpeg"});
db.user.insert(document)
document=({"user_id":"00000002", "user_name":"shiqiqi", "password":"123456", "email":"shiqiqi@gmail.com", "phone":"4121234567", "birth":new Date('May 16, 1991'),"trip_id":[1,5],"friend_id":["00000002","00000003"],"trip_list":[null],"icon_url":"http://bic.cs.cmu.edu/Students/studentpics/Shi,%20Qiqi.jpeg"});
db.user.insert(document)
document=({"user_id":"00000003", "user_name":"zhuangqiankun", "password":"123456", "email":"zhuangqiankun@gmail.com", "phone":"4125204002", "birth":new Date('May 16, 1991'),"trip_id":[3,4,5],"friend_id":[null],"trip_list":[null],"icon_url":"http://bic.cs.cmu.edu/Students/studentpics/Zhuang,%20Quankun.jpeg"});
db.user.insert(document)
document=({"user_id":"00000004", "user_name":"chenglienanjie", "password":"123456", "email":"chenglienanjie@gmail.com", "phone":"4125204000", "birth":new Date('May 16, 1991'),"trip_id":[4],"friend_id":[null],"trip_list":[null],"icon_url":"http://bic.cs.cmu.edu/Students/studentpics/Chenglie,%20Nan.jpeg"});
db.user.insert(document)
document=({"user_id":"00000005", "user_name":"xiaolei", "password":"123456", "email":"xiaolei@gmail.com", "phone":"4125204000", "birth":new Date('May 16, 1991'),"trip_id":[5],"friend_id":[null],"trip_list":[null],"icon_url":"http://bic.cs.cmu.edu/Students/studentpics/Xiao,%20Lei.jpeg"});
db.user.insert(document)
document=({"user_id":"00000006",  "user_name":"zhanxiaoran", "password":"123456", "email":"zhanxiaoran@gmail.com", "phone":"4125204000", "birth":new Date('May 16, 1991'),"trip_id":[6],"friend_id":[null],"trip_list":[null],"icon_url":"http://bic.cs.cmu.edu/Students/studentpics/Zhan,%20Xiaoran.jpeg"});
db.user.insert(document)
document=({"user_id":"00000007", "user_name":"ranchenyang", "password":"123456", "email":"ranchenyang@gmail.com", "phone":"4125204000", "birth":new Date('May 16, 1991'),"trip_id":[7],"friend_id":[null],"trip_list":[null],"icon_url":"http://bic.cs.cmu.edu/Students/studentpics/Ran,%20Chenyang.jpeg"});
db.user.insert(document)
document=({"user_id":"00000008", "user_name":"liuzhiyue", "password":"123456", "email":"liuzhiyue@gmail.com", "phone":"4125204000", "birth":new Date('May 16, 1991'),"trip_id":[8],"friend_id":[null],"trip_list":[null],"icon_url":"http://bic.cs.cmu.edu/Students/studentpics/Liu,%20Zhiyue.jpeg"});
db.user.insert(document)


document=({"trip_id":1,"destination":"Seattle","depart_date":new Date('March 24, 2015'),"return_date":new Date('March 25, 2015'),"a_id":[1,2,3,4],"img_url":"","attraction":""});
db.trip.insert(document)
document=({"trip_id":2,"destination":"Kirkland","depart_date":new Date('Jan 10, 2012'),"return_date":new Date('Jan 16, 2012'),"a_id":[3,4,5],"img_url":"","attraction":""});
db.trip.insert(document)
document=({"trip_id":3,"destination":"Redmond","depart_date":new Date('March 14, 2014'),"return_date":new Date('March 16, 2014'),"a_id":[1,2,3],"img_url":"","attraction":""});
db.trip.insert(document)
document=({"trip_id":4,"destination":"Seattle","depart_date":new Date('May 15, 2014'),"return_date":new Date('May 18, 2014'),"a_id":[2,3,4],"img_url":""});
db.trip.insert(document)
document=({"trip_id":5,"destination":"Seattle","depart_date":new Date('June 10, 2014'),"return_date":new Date('June 16, 2014'),"a_id":[1,2,3],"img_url":"","attraction":""});
db.trip.insert(document)
document=({"trip_id":6,"destination":"Kirkland","depart_date":new Date('Jan 10, 2014'),"return_date":new Date('Jan 16, 2014'),"a_id":[1,2,3],"img_url":"","attraction":""});
db.trip.insert(document)
document=({"trip_id":7,"destination":"Seattle","depart_date":new Date('Jan 17, 2014'),"return_date":new Date('Jan 20, 2014'),"a_id":[1,2,3],"img_url":"","attraction":""});
db.trip.insert(document)


db.Seattle.insert({ "place_id" : "Seattle_00000000", "img_url":"http://a3.urbancdn.com/w/s/VP/oSKlyigGFiBPeE-640m.jpg","address" : "\n\t\t\t1620 BroadwaySeattle, WA 98122\n\t\t", "category_str_list" : [ "Ice Cream & Frozen Yogurt" ], "comment" : "I love all those options for yogurt flavors and toppings.", "desc" : "Yogurtland", "google_geometry" : [ { "address_components" : [ { "long_name" : "1620", "short_name" : "1620", "types" : [ "street_number" ] }, { "long_name" : "Broadway", "short_name" : "Broadway", "types" : [ "route" ] }, { "long_name" : "Capitol Hill", "short_name" : "Capitol Hill", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "administrative_area_level_3", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98122", "short_name" : "98122", "types" : [ "postal_code" ] } ], "formatted_address" : "1620 Broadway, Seattle, WA 98122, USA", "geometry" : { "location" : { "lat" : 47.6162747, "lng" : -122.3205492 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.6176236802915, "lng" : -122.3192002197085 }, "southwest" : { "lat" : 47.6149257197085, "lng" : -122.3218981802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/yogurtland-Seattle", "price_range" : 1, "rating_string" : "4.5", "review_count" : "275", "title" : "Yogurtland" });
db.Seattle.insert({ "place_id" : "Seattle_00000001", "img_url":"https://geo0.ggpht.com/cbk?output=tile&cb_client=maps_sv.gps&panoid=lhYAEVzD_xNc5r-E6nJQ0Q&x=0&y=0&zoom=5","address" : "\n\t\t\t2226 1st AveSeattle, WA 98121\n\t\t", "category_str_list" : [ "Italian", "Tapas/Small Plates" ], "comment" : "I LOVE LOVE LOVE the gnocchi with black truffle cream.", "desc" : "List", "google_geometry" : [ { "address_components" : [ { "long_name" : "2226", "short_name" : "2226", "types" : [ "street_number" ] }, { "long_name" : "1st Avenue", "short_name" : "1st Ave", "types" : [ "route" ] }, { "long_name" : "Belltown", "short_name" : "Belltown", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98121", "short_name" : "98121", "types" : [ "postal_code" ] } ], "formatted_address" : "2226 1st Avenue, Seattle, WA 98121, USA", "geometry" : { "location" : { "lat" : 47.6126467, "lng" : -122.3455715 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.6139956802915, "lng" : -122.3442225197085 }, "southwest" : { "lat" : 47.6112977197085, "lng" : -122.3469204802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/list-Seattle", "price_range" : 2, "rating_string" : "4.5", "review_count" : "610", "title" : "List" });
db.Seattle.insert({ "place_id" : "Seattle_00000002", "img_url":"http://www.seattle.gov/tour/images/locks10.jpg","address" : "\n\t\t\t3015 NW 54th StSeattle, WA 98107\n\t\t", "category_str_list" : [ "Landmarks & Historical Buildings", "Lakes" ], "comment" : "Make sure to check out the salmon at the fish ladder.", "desc" : "Hiram M. Chittenden Locks", "google_geometry" : [ { "address_components" : [ { "long_name" : "3015", "short_name" : "3015", "types" : [ "street_number" ] }, { "long_name" : "Northwest 54th Street", "short_name" : "NW 54th St", "types" : [ "route" ] }, { "long_name" : "Old Ballard", "short_name" : "Old Ballard", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98107", "short_name" : "98107", "types" : [ "postal_code" ] } ], "formatted_address" : "3015 Northwest 54th Street, Seattle, WA 98107, USA", "geometry" : { "location" : { "lat" : 47.6667052, "lng" : -122.3980679 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.66805418029149, "lng" : -122.3967189197085 }, "southwest" : { "lat" : 47.66535621970849, "lng" : -122.3994168802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/hiram-m-chittenden-locks-Seattle", "price_range" : 0, "rating_string" : "4.5", "review_count" : "219", "title" : "Hiram M. Chittenden Locks" });
db.Seattle.insert({ "place_id" : "Seattle_00000003", "img_url":"http://s3-media4.fl.yelpcdn.com/bphoto/NFkS-qBskwoqQDQvnFocOw/l.jpg","address" : "\n\t\t\t6418 20th Ave NWSeattle, WA 98107\n\t\t", "category_str_list" : [ "Jewelry", "Accessories" ], "comment" : "with such a great assortment of unique purses and jewelry.", "desc" : "Laura Bee Designs", "google_geometry" : [ { "address_components" : [ { "long_name" : "6418", "short_name" : "6418", "types" : [ "street_number" ] }, { "long_name" : "20th Avenue Northwest", "short_name" : "20th Ave NW", "types" : [ "route" ] }, { "long_name" : "Old Ballard", "short_name" : "Old Ballard", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98107", "short_name" : "98107", "types" : [ "postal_code" ] } ], "formatted_address" : "6418 20th Avenue Northwest, Seattle, WA 98107, USA", "geometry" : { "location" : { "lat" : 47.6757615, "lng" : -122.381931 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.6771104802915, "lng" : -122.3805820197085 }, "southwest" : { "lat" : 47.6744125197085, "lng" : -122.3832799802915 } } }, "partial_match" : true, "types" : [ "street_address" ] } ], "link" : "/biz/laura-bee-designs-Seattle", "price_range" : 2, "rating_string" : "5.0", "review_count" : "53", "title" : "Laura Bee Designs" });
db.Seattle.insert({ "place_id" : "Seattle_00000004", "img_url":"http://s3-media3.fl.yelpcdn.com/bphoto/LwpjIQCb_P_0vCDCQC8PDA/o.jpg","address" : "\n\t\t\t2724 1st Ave SSeattle, WA 98134\n\t\t", "category_str_list" : [ "Hair Salons", "Vinyl Records" ], "comment" : "If you need a top notch guy hair cut, Martin is your guy.", "desc" : "Radar Hair & Records", "google_geometry" : [ { "address_components" : [ { "long_name" : "2724", "short_name" : "2724", "types" : [ "street_number" ] }, { "long_name" : "1st Avenue South", "short_name" : "1st Avenue South", "types" : [ "route" ] }, { "long_name" : "Industrial District East", "short_name" : "Industrial District East", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98134", "short_name" : "98134", "types" : [ "postal_code" ] } ], "formatted_address" : "2724 1st Avenue South, Seattle, WA 98134, USA", "geometry" : { "location" : { "lat" : 47.57893199999999, "lng" : -122.333697 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.58028098029149, "lng" : -122.3323480197085 }, "southwest" : { "lat" : 47.57758301970849, "lng" : -122.3350459802915 } } }, "partial_match" : true, "types" : [ "street_address" ] } ], "link" : "/biz/radar-hair-and-records-Seattle-2", "price_range" : 2, "rating_string" : "5.0", "review_count" : "101", "title" : "Radar Hair & Records" });
db.Seattle.insert({ "place_id" : "Seattle_00000005", "img_url":"https://fbcdn-sphotos-g-a.akamaihd.net/hphotos-ak-xaf1/v/t1.0-9/292511_10151509941640105_1230415579_n.jpg?oh=ee72b8d04e257d8149840ed3ae9453fa&oe=5577D728&__gda__=1435358371_749d03db3db161d6c3c4599e1bd2d4d7", "address" : "\n\t\t\t1000 First AvenueSeattle, WA 98104\n\t\t", "category_str_list" : [ "Hotels" ], "comment" : "Floor to ceiling windows facing the bay and the stadiums.", "desc" : "Hotel 1000", "google_geometry" : [ { "address_components" : [ { "long_name" : "1000", "short_name" : "1000", "types" : [ "street_number" ] }, { "long_name" : "1st Avenue", "short_name" : "1st Ave", "types" : [ "route" ] }, { "long_name" : "Central Business District", "short_name" : "Central Business District", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98104", "short_name" : "98104", "types" : [ "postal_code" ] } ], "formatted_address" : "1000 1st Avenue, Seattle, WA 98104, USA", "geometry" : { "location" : { "lat" : 47.605049, "lng" : -122.336106 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.6063979802915, "lng" : -122.3347570197085 }, "southwest" : { "lat" : 47.6037000197085, "lng" : -122.3374549802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/hotel-1000-seattle", "price_range" : 3, "rating_string" : "4.5", "review_count" : "252", "title" : "Hotel 1000" });
db.Seattle.insert({ "place_id" : "Seattle_00000006", "img_url":"http://www.mrgyroseattle.com/images/home/05.jpg", "address" : "\n\t\t\t8411 Greenwood Ave NSeattle, WA 98103\n\t\t", "category_str_list" : [ "Sandwiches", "Greek", "Middle Eastern" ], "comment" : "A must try for anyone who loves a good Gyro.", "desc" : "Mr. Gyros", "google_geometry" : [ { "address_components" : [ { "long_name" : "8411", "short_name" : "8411", "types" : [ "street_number" ] }, { "long_name" : "Greenwood Avenue North", "short_name" : "Greenwood Ave N", "types" : [ "route" ] }, { "long_name" : "Greenwood", "short_name" : "Greenwood", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98103", "short_name" : "98103", "types" : [ "postal_code" ] } ], "formatted_address" : "8411 Greenwood Avenue North, Seattle, WA 98103, USA", "geometry" : { "location" : { "lat" : 47.6902581, "lng" : -122.3555547 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.6916070802915, "lng" : -122.3542057197085 }, "southwest" : { "lat" : 47.68890911970851, "lng" : -122.3569036802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/mr-gyros-seattle", "price_range" : 1, "rating_string" : "4.5", "review_count" : "522", "title" : "Mr. Gyros" });
db.Seattle.insert({ "place_id" : "Seattle_00000007", "img_url":"http://www.seattleattractions.com/wp-content/uploads/2013/05/chihuly.jpg", "address" : "\n\t\t\t305 Harrison StSeattle, WA 98109\n\t\t", "category_str_list" : [ "Art Galleries", "Museums" ], "comment" : "It's a great area, right near the Space Needle and EMP museum.", "desc" : "Chihuly Garden and Glass", "google_geometry" : [ { "address_components" : [ { "long_name" : "305", "short_name" : "305", "types" : [ "street_number" ] }, { "long_name" : "Harrison Street", "short_name" : "Harrison St", "types" : [ "route" ] }, { "long_name" : "South-Lake Union", "short_name" : "South-Lake Union", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98109", "short_name" : "98109", "types" : [ "postal_code" ] } ], "formatted_address" : "305 Harrison Street, Seattle, WA 98109, USA", "geometry" : { "location" : { "lat" : 47.62048160000001, "lng" : -122.3504451 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.62183058029151, "lng" : -122.3490961197085 }, "southwest" : { "lat" : 47.61913261970851, "lng" : -122.3517940802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/chihuly-garden-and-glass-seattle-2", "price_range" : 2, "rating_string" : "4.5", "review_count" : "266", "title" : "Chihuly Garden and Glass" });
db.Seattle.insert({ "place_id" : "Seattle_00000008", "img_url":"http://www.djc.com/stories/images/20120629/CH_PacificSunan%20Glasshouseevening_big.jpg","address" : "\n\t\t\t345 15th Ave ESeattle, WA 98112\n\t\t", "category_str_list" : [ "Coffee & Tea", "Tea Rooms" ], "comment" : "I love this place and I love that all the teas are organic.", "desc" : "Remedy Teas", "google_geometry" : [ { "address_components" : [ { "long_name" : "345", "short_name" : "345", "types" : [ "street_number" ] }, { "long_name" : "15th Avenue East", "short_name" : "15th Ave E", "types" : [ "route" ] }, { "long_name" : "Capitol Hill", "short_name" : "Capitol Hill", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98112", "short_name" : "98112", "types" : [ "postal_code" ] } ], "formatted_address" : "345 15th Avenue East, Seattle, WA 98112, USA", "geometry" : { "location" : { "lat" : 47.6217996, "lng" : -122.3129002 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.6231485802915, "lng" : -122.3115512197085 }, "southwest" : { "lat" : 47.6204506197085, "lng" : -122.3142491802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/remedy-teas-seattle", "price_range" : 2, "rating_string" : "4.5", "review_count" : "327", "title" : "Remedy Teas" });
db.Seattle.insert({ "place_id" : "Seattle_00000009", "img_url":"http://farm4.static.flickr.com/3450/5720841626_76052c2f54.jpg","address" : "\n\t\t\t1416 34th AveSeattle, WA 98122\n\t\t", "category_str_list" : [ "Wine Bars", "Tapas/Small Plates" ], "comment" : "We also had the pleasure of meeting Henri, the owner.", "desc" : "Bottlehouse", "google_geometry" : [ { "address_components" : [ { "long_name" : "1416", "short_name" : "1416", "types" : [ "street_number" ] }, { "long_name" : "34th Avenue", "short_name" : "34th Ave", "types" : [ "route" ] }, { "long_name" : "Central District", "short_name" : "Central District", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98122", "short_name" : "98122", "types" : [ "postal_code" ] } ], "formatted_address" : "1416 34th Avenue, Seattle, WA 98122, USA", "geometry" : { "location" : { "lat" : 47.613459, "lng" : -122.288968 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.61480798029149, "lng" : -122.2876190197085 }, "southwest" : { "lat" : 47.6121100197085, "lng" : -122.2903169802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/bottlehouse-seattle", "price_range" : 2, "rating_string" : "4.5", "review_count" : "106", "title" : "Bottlehouse" });
db.Seattle.insert({ "place_id" : "Seattle_00000010", "img_url":"http://media-cdn.tripadvisor.com/media/photo-s/02/49/02/43/bottle-house-1.jpg", "address" : "\n\t\t\t1054 N 39th StSeattle, WA 98103\n\t\t", "category_str_list" : [ "American (New)", "Greek" ], "comment" : "It also gave us a chance to chat with Chef Dustin.", "desc" : "Art of The Table", "google_geometry" : [ { "address_components" : [ { "long_name" : "1054", "short_name" : "1054", "types" : [ "street_number" ] }, { "long_name" : "North 39th Street", "short_name" : "N 39th St", "types" : [ "route" ] }, { "long_name" : "Fremont", "short_name" : "Fremont", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98103", "short_name" : "98103", "types" : [ "postal_code" ] } ], "formatted_address" : "1054 North 39th Street, Seattle, WA 98103, USA", "geometry" : { "location" : { "lat" : 47.6541077, "lng" : -122.3441178 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.65545668029149, "lng" : -122.3427688197085 }, "southwest" : { "lat" : 47.6527587197085, "lng" : -122.3454667802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/art-of-the-table-seattle", "price_range" : 4, "rating_string" : "4.5", "review_count" : "303", "title" : "Art of The Table" });
db.Seattle.insert({ "place_id" : "Seattle_00000011", "img_url":"http://www.experiencegr.com/blog/wp-content/uploads/2013/12/storefront2.jpg", "address" : "\n\t\t\t520 Pike StSeattle, WA 98101\n\t\t", "category_str_list" : [ "Coffee & Tea" ], "comment" : "I am even sipping the most amazing Egg Nog Latte right now.", "desc" : "Monorail Espresso", "google_geometry" : [ { "address_components" : [ { "long_name" : "520", "short_name" : "520", "types" : [ "street_number" ] }, { "long_name" : "Pike Street", "short_name" : "Pike St", "types" : [ "route" ] }, { "long_name" : "Central Business District", "short_name" : "Central Business District", "types" : [ "neighborhood", "political" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] }, { "long_name" : "98101", "short_name" : "98101", "types" : [ "postal_code" ] } ], "formatted_address" : "520 Pike Street, Seattle, WA 98101, USA", "geometry" : { "location" : { "lat" : 47.611234, "lng" : -122.334994 }, "location_type" : "ROOFTOP", "viewport" : { "northeast" : { "lat" : 47.6125829802915, "lng" : -122.3336450197085 }, "southwest" : { "lat" : 47.6098850197085, "lng" : -122.3363429802915 } } }, "types" : [ "street_address" ] } ], "link" : "/biz/monorail-espresso-seattle", "price_range" : 1, "rating_string" : "4.5", "review_count" : "243", "title" : "Monorail Espresso" });
db.Seattle.insert({ "place_id" : "Seattle_00000012", "img_url":"https://c1.staticflickr.com/9/8043/8131858665_28f8d105e3_z.jpg","address" : "\n\t\t\t1521 10th AveSeattle, WA 98122\n\t\t", "category_str_list" : [ "Bookstores" ], "comment" : "is classic Seattle, and simply the best bookstore in town.", "desc" : "The Elliott Bay Book Company", "google_geometry" : [ { "address_components" : [ { "long_name" : "98122", "short_name" : "98122", "types" : [ "postal_code" ] }, { "long_name" : "Seattle", "short_name" : "Seattle", "types" : [ "locality", "political" ] }, { "long_name" : "King", "short_name" : "King", "types" : [ "administrative_area_level_2", "political" ] }, { "long_name" : "Washington", "short_name" : "WA", "types" : [ "administrative_area_level_1", "political" ] }, { "long_name" : "United States", "short_name" : "US", "types" : [ "country", "political" ] } ], "formatted_address" : "Seattle, WA 98122, USA", "geometry" : { "bounds" : { "northeast" : { "lat" : 47.625468, "lng" : -122.263535 }, "southwest" : { "lat" : 47.590821, "lng" : -122.3290361 } }, "location" : { "lat" : 47.6087583, "lng" : -122.2964235 }, "location_type" : "APPROXIMATE", "viewport" : { "northeast" : { "lat" : 47.625468, "lng" : -122.263535 }, "southwest" : { "lat" : 47.590821, "lng" : -122.3290361 } } }, "partial_match" : true, "types" : [ "postal_code" ] } ], "link" : "/biz/the-elliott-bay-book-company-seattle", "price_range" : 2, "rating_string" : "4.5", "review_count" : "315", "title" : "The Elliott Bay Book Company" });

document=({"a_id":1,"start_time":new Date("2014-05-15T14:00:00Z"), "end_time":new Date("2014-05-15T16:00:00Z"),"place_id":"Seattle_00000000", "trip_id":1})
db.activity.insert(document)
document=({"a_id":2,"start_time":new Date("2014-06-11T14:00:00Z"), "end_time":new Date("2014-06-11T18:00:00Z"),"place_id":"Seattle_00000001", "trip_id":1})
db.activity.insert(document)
document=({"a_id":3,"start_time":new Date("2014-05-15T14:00:00Z"), "end_time":new Date("2014-05-15T16:00:00Z"),"place_id":"Seattle_00000002", "trip_id":1})
db.activity.insert(document)
document=({"a_id":4,"start_time":new Date("2014-06-11T14:00:00Z"), "end_time":new Date("2014-06-11T18:00:00Z"),"place_id":"Seattle_00000003", "trip_id":1})
db.activity.insert(document)
document=({"a_id":5,"start_time":new Date("2014-05-15T14:00:00Z"), "end_time":new Date("2014-05-15T16:00:00Z"),"place_id":"Seattle_00000004", "trip_id":1})
db.activity.insert(document)
document=({"a_id":6,"start_time":new Date("2014-06-11T14:00:00Z"), "end_time":new Date("2014-06-11T18:00:00Z"),"place_id":"Seattle_00000005", "trip_id":1})
db.activity.insert(document)
document=({"a_id":7,"start_time":new Date("2014-05-15T14:00:00Z"), "end_time":new Date("2014-05-15T16:00:00Z"),"place_id":"Seattle_00000006", "trip_id":1})
db.activity.insert(document)
document=({"a_id":8,"start_time":new Date("2014-06-11T14:00:00Z"), "end_time":new Date("2014-06-11T18:00:00Z"),"place_id":"Seattle_00000007", "trip_id":1})
db.activity.insert(document)
document=({"a_id":9,"start_time":new Date("2014-06-11T14:00:00Z"), "end_time":new Date("2014-06-11T18:00:00Z"),"place_id":"Seattle_00000008", "trip_id":1})
db.activity.insert(document)
document=({"a_id":10,"start_time":new Date("2014-06-11T14:00:00Z"), "end_time":new Date("2014-06-11T18:00:00Z"),"place_id":"Seattle_00000009", "trip_id":1})
db.activity.insert(document)
document=({"a_id":11,"start_time":new Date("2014-06-11T14:00:00Z"), "end_time":new Date("2014-06-11T18:00:00Z"),"place_id":"Seattle_00000010", "trip_id":1})
db.activity.insert(document)
document=({"a_id":12,"start_time":new Date("2014-06-11T14:00:00Z"), "end_time":new Date("2014-06-11T18:00:00Z"),"place_id":"Seattle_00000011", "trip_id":1})
db.activity.insert(document)

document=({"dest":"Seattle", "img_url":"http://upload.wikimedia.org/wikipedia/commons/2/2f/Space_Needle002.jpg","attraction":"Chihuly Garden and Glass, Space Needle, Museum of Flight"})
db.city.insert(document)
document=({"dest":"Kirkland", "img_url":"http://upload.wikimedia.org/wikipedia/commons/7/71/Kirkland_waterfront.jpg","attraction":"Juanita Bay Park, Marina Park, Juanita Beach Park"})
db.city.insert(document)
document=({"dest":"Redmond", "img_url":"http://upload.wikimedia.org/wikipedia/commons/1/16/Bicycle_Capital_of_the_Northwest.JPG","attraction":"Marymoor Park, Idylwood Beach Park, Microsoft Visitor Center"})
db.city.insert(document)
document=({"dest":"Bellevue", "img_url":"http://upload.wikimedia.org/wikipedia/commons/2/21/Aerial_Bellevue_Washington_November_2011.jpg","attraction":"Bellevue Botanical Garden, Downtown Park, Mercer Slough Nature Park"})
db.city.insert(document)