modelConnectionString : flydragon.cloudapp.net:27017
modelDataBaseName : MONKModel
dataConnectionString : flydragon.cloudapp.net:27017
dataDataBaseName : MONKData
uidConnectionString : flydragon.cloudapp.net:27017
uidDataBaseName : uidDB
loggingConfig:
    version : 1
    disable_existing_loggers : True
    formatters : 
        verbose : 
            format : '[%(asctime)s][%(process)-5d][%(name)-12s][%(levelname)-8s][%(lineno)-4d] : %(message)s'
        simple :
            format : '[%(name)-12s][%(levelname)-8s][%(process)d] : %(message)s'
    handlers :
        console :
            class : logging.StreamHandler
            formatter : simple
            stream : ext://sys.stdout
        files :
            formatter : verbose
            class : logging.handlers.RotatingFileHandler
            filename : logs/monk.log
            maxBytes : 1000000
            backupCount: 10
    loggers :
        monk :
            level : DEBUG
            propagate : True
        kafka :
            level : ERROR
            propagate : True
    root :
        level : DEBUG
        handlers : [console, files]
        