kafkaConnectionString : monkbus.cloudapp.net:9092,monkbus.cloudapp.net:9093,monkbus.cloudapp.net:9094
mongoConnectionString : localhost:27017
dataDataBaseName: TravelGene 
entityCollectionName: Seattle
